default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ota

development:
  <<: *default
  database: saperi_development

test:
  <<: *default
  database: saperi_test

production:
  <<: *default
  database: saperi_production
  password: <%= ENV['SAPERI_DATABASE_PASSWORD'] %>


